.TH helios 7 "April 2024"
.SH NAME
Helios - An intelligent music recommendation platform.

.SH SYNOPSIS
Helios is an intelligent music recommendation platform.

.SH DESCRIPTION
Helios consists of an ensemble of software. These are a selection of mostly
command line tools described below in \fBSEE ALSO\fR and the \fBheliosd\fR
server.

The \fBheliosd\fR system service provides an embedded HTTP server which exports
a RESTful API available to power web-based or other types of applications. The
API can be used for managing a catalogue, performing analysis, and discovering
music. Virtually everything the REST API can do is accessible from the command
line tools.

The \fBhelios-add-song\fR(1), \fBhelios-delete-song\fR(1),
\fBhelios-download-song\fR(1), \fBhelios-find-servers\fR(1),
\fBhelios-get-song\fR(1), \fBhelios-import-songs\fR(1), \fBhelios-learn\fR(1),
\fBhelios-modify-song\fR(1), \fBhelios-similar\fR(1), \fBhelios-status\fR(1),
and \fBhelios-trainer\fR(1) utilities are all provided by the
\fIhelios-client-utilities\fR package; the \fBheliosd\fR(1) daemon by the
\fIhelios-server\fR package; the database backend by the
\fIhelios-database-local\fR package; and the pure Python 3 client API module by
the \fIpython3-helios-client\fR package.

All of the utilities that ship with the \fIhelios-client-utilities\fR package
were written in Python using the \fIpython3-helios-client\fR module. They can
serve as examples on how to use the Python client module to get Helios
integrated into your platform as quickly as possible.

.SH AUTHOR
Cartesian Theatre <info@cartesiantheatre.com>

.SH REPORTING BUGS
Report bugs to Cartesian Theatre <info@cartesiantheatre.com>.

.SH COPYRIGHT
Copyright (C) 2015-2024 Cartesian Theatre. All rights reserved.

.SH SEE ALSO
\fBheliosd\fR(1)
.br
\fBhelios-add-song\fR(1)
.br
\fBhelios-delete-song\fR(1)
.br
\fBhelios-download-song\fR(1)
.br
\fBhelios-find-servers\fR(1)
.br
\fBhelios-get-song\fR(1)
.br
\fBhelios-import-songs\fR(1)
.br
\fBhelios-learn\fR(1)
.br
\fBhelios-modify-song\fR(1)
.br
\fBhelios-provision-magnatune\fR(1)
.br
\fBhelios-similar\fR(1)
.br
\fBhelios-status\fR(1)
.br
\fBhelios-trainer\fR(1)
.br

\fIhttps://www.heliosmusic.io\fR
.br

