.TH helios-provision-magnatune 1 "June 2022"
.SH NAME
helios-provision-magnatune - Download Magnatune catalogue and generate CSV for \fBhelios-import-songs\fR(1)

.SH SYNOPSIS
.B helios-provision-magnatune\fR --user=\fI<user>\fR [\fIOPTIONS\fR] [\fIoutput_directory\fR]

.SH DESCRIPTION
This utility is useful for rapid deployment of a \fBheliosd\fR(1) server with a sample catalogue, perhaps for demonstration purposes. It will download songs from the Magnatune's remote service into the requested \fIoutput_directory\fR. This is the current working directory by default.

A comma delimited CSV file named \fImagnatune.csv\fR, unless overridden, will be generated within  the \fIoutput_directory\fR upon completion. This CSV file is suitable for use with the \fBhelios-import-songs\fR(1) utility for a subsequent batch import. The format of this file is described in greater detail in \fBhelios-import-songs\fR(1).

The total time necessary to download the requested songs from the remote Magnatune service depends on the current size of the available catalogue, the number of songs requested, and the available bandwidth.

Note that you must have prior authorization from Magnatune in order to use any of its music for commercial purposes.

.SH OPTIONS

.TP
\fB\--absolute-path\fR
Write absolute path to every song instead of just the file name within the generated CSV. By default only the file name is written out. Note that if you use this switch and you plan on moving the location of the downloaded songs later, the paths in the CSV will become invalidated.

.TP
\fB\--cached-sqlite\fR \fI<sqlite_database.db>\fR
Don't attempt to retrieve the SQLite database from the remote Magnatune service. Instead use a local cached copy, \fIdatabase.db\fR.

.TP
\fB\--cover-artwork\fR
If a song does not contain embedded cover art, ask Magnatune for it and then embed it in the file if supported.

.TP
\fB\--cover-artwork-archive\fR \fI<output_directory>\fR
Archive a copy of each song's cover art in all available dimensions in \fIoutput_directory\fR. Each song will have a corresponding \fIsong_reference_WIDTHxHEIGHT.jpg\fR saved within this directory where WIDTH and HEIGHT are values denoting the image's square dimension of 50, 75, 100, 160, 200, 300, 600, or 1400 pixels. This switch may still be used absent \fI--cover-artwork\fR.

.TP
\fB\--force-overwrite\fR
By default songs that are already present in the \fIoutput_directory\fR are not downloaded again. Use this switch to force an overwrite with a fresh download. Note that if the local copy is in a different format than the requested format, the songs will not be considered the same.

.TP
\fB\--format\fR \fIwav|mp3|alac|vorbis\fR
Format to download requested songs in. The wave format is raw uncompressed. The MP3 format is high quality VBR encoded, but does not refer to the lower quality 128k that is also available from Magnatune. The ALAC format is lossless compressed within an M4A container. The high quality Vorbis encoded audio is stored within an Ogg container. The default is vorbis.

.TP
\fB\--genre\fR \fIclassical|new-age|electronica|world|ambient|jazz|hip-hop|alt-rock|electro-rock|hard-rock\fR
By default music of any genre will be downloaded. Use this switch to limit downloads to only the selected genre as defined by Magnatune.

.TP
\fB\--maximum-errors\fR \fI<max>\fR
Maximum number of errors to tolerate before exiting. The default is one. Set to zero for unlimited non-fatal errors.

.TP
\fB\--minimum-length\fR \fI<seconds>\fR
Only consider songs at least \fI<seconds>\fR in length. The default is zero, or any length.

.TP
\fB\--output-csv\fR \fI<catalogue_csv>\fR
A comma delimited CSV file will be generated upon completion and suitable for use with \fBhelios-import-songs\fR(1). The default is \fIoutput_directory/magnatune.csv\fR, unless overridden with this switch.

.TP
\fB\--password\fR \fI<user>\fR
Password to use when authenticating as \fI<user>\fR with the remote Magnatune service. If the password cannot be retrieved from the system keyring and is not explicitly provided, the user will automatically be prompted at runtime.

.TP
\fB\--random\fR
If \fB\--song-count\fR \fI<count>\fR is greater than zero, but less than the total size of the available Magnatune catalogue, randomly select \fI<count>\fR songs to download.

.TP
\fB\--song-count\fR \fI<count>\fR
Number of songs to attempt to download. The default is zero, or all of them.

.TP
\fB\--user\fR \fI<user>\fR
User name to use when authenticating with the remote Magnatune service. This is a required argument.

.TP
\fB\--verbose\fR
Be verbose by showing additional information.

.TP
\fB\--version\fR
Show version of utility.

.SH EXAMPLES

Authenticate as user \fIme\fR with the remote Magnatune service. Download 25 random Alt Rock songs into the \fIcatalogue\fR directory. Each song must be at least two minutes in length and encoded in the Ogg/Vorbis format. Verify that album artwork is present in every song, automatically retrieving and embedding the correct artwork if it was not already present in the song.

.BR
$ helios-provision-magnatune --user me --format vorbis --song-count=25 --random --genre alt-rock --cover-artwork --minimum-length=120 catalogue/ --cover-artwork-archive artwork/

.BR
$ cat catalogue/magnatune.csv
    ...
    "MAGNATUNE_06_FUNKY_BREEZE_COZMIKBEATS_MP3", "Some album", "Some artist", "Some \"title\"", "Some genre", "USA2P0502717", "135.72", "2003", "some_song.flac"
    ...

.SH NOTES

During a session you will see output similar to the following:

    ...
    12:44:34: [23246] Downloading song 19578/20888: Archiving 200x200 album artwork...
    12:44:34: [23246] Downloading song 19578/20888: Archiving 300x300 album artwork...
    12:44:34: [23246] Downloading song 19578/20888: Archiving 600x600 album artwork...
    12:44:35: [23246] Downloading song 19578/20888: Archiving 1400x1400 album artwork...
    12:44:36: [23246] Downloading song 19578/20888: 03-The Sound-Toni Castells.mp3
    12:44:39: [23247] Downloading song 19579/20888: Archiving 50x50 album artwork...
    12:44:39: [23247] Downloading song 19579/20888: Archiving 75x75 album artwork...
    ...

The tool logs on each line every step it takes to retrieve the catalogue. From left to right you can read this as the time stamp the activity took place on, the Magnatune issued song ID, a descriptive explanation on what is being done, and the latter containing the current progress.

In the above example the last line reads that at 12:44:39 a song with Magnatune ID 23247 had its album artwork fetched at 75x75 dimensions as part of song 19579 of 20888 that is currently scheduled to be retrieved.

.SH EXIT STATUS
\fBhelios-provision-magnatune\fR exits with a status of zero if no errors occurred.

.SH AUTHOR
Cartesian Theatre <info@cartesiantheatre.com>

.SH REPORTING BUGS
Report bugs to Cartesian Theatre <info@cartesiantheatre.com>

.SH COPYRIGHT
Copyright (C) 2015-2022 Cartesian Theatre. All rights reserved.

.SH SEE ALSO

\fBhelios\fR(7)
.BR

\fBhelios-import-songs\fR(1)
.BR

\fIhttps://www.heliosmusic.io\fR
.BR

